import os

html_template = """<!DOCTYPE html>
<html>
<head>
    <title>Decoy B — 3D Structural Similarity Viewer</title>
    <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
    <style>
        body { margin: 0; padding: 0; font-family: Arial, sans-serif; background: #1e1e1e; color: #fff; }
        #viewer { width: 100vw; height: 80vh; position: relative; }
        #controls { padding: 20px; text-align: center; }
        .legend-item { display: inline-block; margin: 0 15px; padding: 5px 10px; border-radius: 4px; font-weight: bold; }
        .target-col { background: #ff4757; color: white; }
        .decoy-col { background: #1e90ff; color: white; }
        .hla-col { background: #576574; color: white; }
    </style>
</head>
<body>
    <div id="viewer"></div>
    <div id="controls">
        <h2>Target pMHC vs Decoy B pMHC 3D Alignment</h2>
        <p><strong>Target:</strong> GILGFVFTL (HLA-A*02:01) &nbsp; | &nbsp; <strong>Decoy B:</strong> GPLGFVIYL (HD=3, CosSim=0.987)</p>
        <div class="legend-item target-col">Target Peptide (GILGFVFTL)</div>
        <div class="legend-item decoy-col">Decoy B Peptide (GPLGFVIYL)</div>
        <div class="legend-item hla-col">HLA Groove (A*02:01)</div>
        <br><br>
        <p><em>Notice how the central TCR contact residues (p4-p8) overlap perfectly in 3D space, despite sequence mismatch!</em></p>
    </div>
    
    <script>
        $(function() {
            let element = $('#viewer');
            let config = { backgroundColor: '#1e1e1e' };
            let viewer = $3Dmol.createViewer(element, config);

            // Fetch the generated PDBs (Assuming they are in the data dir)
            // For the sake of demonstration, we instruct the user to load the PDBs generated by tFold/AF3.
            
            alert("This viewer script is ready. Once tFold/AF3 finishes generating the PDBs in data/decoy_b/pmhc_models/, you can map their paths here to visualize the structural overlap.");
        });
    </script>
</body>
</html>
"""

with open("/share/liuyutian/pMHC_decoy_library/figures/decoy_b_viewer.html", "w") as f:
    f.write(html_template)
print("Interactive 3D Viewer template generated at: figures/decoy_b_viewer.html")
