import argparse
from pathlib import Path
import glob

def generate_html(target_pdb: Path, candidate_pdbs: list[Path], output_html: Path):
    target_data = target_pdb.read_text().replace('\n', '\\n').replace("'", "\\'")
    
    cand_data = []
    for p in candidate_pdbs:
        name = p.stem.replace('pmhc_', '').split('_')[0]
        content = p.read_text().replace('\n', '\\n').replace("'", "\\'")
        cand_data.append(f"{{ name: '{name}', data: '{content}' }}")
        
    cand_array_str = ",\n        ".join(cand_data)
    
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>pMHC 3D Structural Viewer</title>
    <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
    <style>
        body {{ margin: 0; padding: 0; font-family: Arial, sans-serif; background: #1e1e1e; color: #fff; }}
        #viewer {{ width: 100vw; height: 80vh; position: relative; }}
        #controls {{ padding: 20px; text-align: center; }}
        .btn {{ padding: 8px 16px; margin: 0 5px; background: #34495e; color: white; border: none; cursor: pointer; border-radius: 4px; }}
        .btn.active {{ background: #1e90ff; }}
        .legend-item {{ display: inline-block; margin: 0 15px; padding: 5px 10px; border-radius: 4px; font-weight: bold; }}
        .target-col {{ background: #ff4757; color: white; }}
        .decoy-col {{ background: #1e90ff; color: white; }}
        .hla-col {{ background: #576574; color: white; }}
    </style>
</head>
<body>
    <div id="viewer"></div>
    <div id="controls">
        <h2>Target pMHC vs Candidate pMHC 3D Alignment</h2>
        <div class="legend-item target-col">Target Peptide ({target_pdb.stem})</div>
        <div class="legend-item hla-col">HLA Groove</div>
        <div class="legend-item decoy-col">Candidate Peptide</div>
        <br><br>
        <div id="cand-buttons">
            <!-- Buttons will be generated here -->
        </div>
    </div>
    
    <script>
        const targetData = '{target_data}';
        const candidates = [
            {cand_array_str}
        ];
        
        let viewer;
        let targetModel;
        let candModel = null;
        
        $(function() {{
            let element = $('#viewer');
            let config = {{ backgroundColor: '#1e1e1e' }};
            viewer = $3Dmol.createViewer(element, config);
            
            // Load Target
            targetModel = viewer.addModel(targetData, 'pdb');
            targetModel.setStyle({{chain: 'M'}}, {{cartoon: {{color: '#576574', opacity: 0.8}}}}); // MHC Heavy
            targetModel.setStyle({{chain: 'N'}}, {{cartoon: {{color: '#a4b0be', opacity: 0.8}}}}); // B2m
            targetModel.setStyle({{chain: 'P'}}, {{stick: {{color: '#ff4757'}}}}); // Target Peptide
            
            viewer.zoomTo();
            viewer.render();
            
            // Setup buttons
            const btnContainer = document.getElementById('cand-buttons');
            candidates.forEach((cand, idx) => {{
                const btn = document.createElement('button');
                btn.className = 'btn';
                btn.textContent = cand.name;
                btn.onclick = () => loadCandidate(idx, btn);
                btnContainer.appendChild(btn);
            }});
            
            if(candidates.length > 0) {{
                loadCandidate(0, btnContainer.children[0]);
            }}
        }});
        
        function loadCandidate(idx, btnElement) {{
            // update active button
            document.querySelectorAll('.btn').forEach(b => b.classList.remove('active'));
            if(btnElement) btnElement.classList.add('active');
            
            if(candModel) {{
                viewer.removeModel(candModel);
            }}
            
            const cand = candidates[idx];
            candModel = viewer.addModel(cand.data, 'pdb');
            
            // We superimpose candModel to targetModel using chain M (HLA groove)
            // But for simple viewing, assuming they are pre-aligned or generated by tFold which naturally aligns them.
            // If they are from tFold, they already share the same frame.
            
            candModel.setStyle({{chain: 'M'}}, {{cartoon: {{hidden: true}}}});
            candModel.setStyle({{chain: 'N'}}, {{cartoon: {{hidden: true}}}});
            candModel.setStyle({{chain: 'P'}}, {{stick: {{color: '#1e90ff'}}}}); // Candidate Peptide
            
            viewer.render();
        }}
    </script>
</body>
</html>
"""
    output_html.parent.mkdir(parents=True, exist_ok=True)
    output_html.write_text(html)
    print(f"Generated 3D Viewer at: {output_html}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--target-pdb", required=True)
    parser.add_argument("--cand-dir", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    
    target_pdb = Path(args.target_pdb)
    cands = list(Path(args.cand_dir).glob("*.pdb"))
    cands = [c for c in cands if c.name != target_pdb.name]
    
    if not cands:
        print(f"No candidate PDBs found in {args.cand_dir}")
    else:
        generate_html(target_pdb, cands, Path(args.output))
